# Generated by Django 4.1.4 on 2023-01-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gmina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("gmi_id", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Wojewodztwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("woj_id", models.CharField(max_length=150, unique=True)),
                ("status_on_day", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Powiat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("pow_id", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
                (
                    "wojewodztwo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.wojewodztwo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Miejscowosc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("miejsc_id", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
                (
                    "gmina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.gmina"
                    ),
                ),
                (
                    "powiat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.powiat"
                    ),
                ),
                (
                    "wojewodztwo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.wojewodztwo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gmina",
            name="powiat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.powiat"
            ),
        ),
        migrations.AddField(
            model_name="gmina",
            name="wojewodztwo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="main.wojewodztwo"
            ),
        ),
    ]
