# Generated by Django 4.1.4 on 2022-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wojewodztwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("woj_id", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
            ],
        ),
    ]
