# Generated by Django 4.1.4 on 2023-01-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ulica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("second_name", models.CharField(max_length=150)),
                ("full_name", models.CharField(max_length=150)),
                ("type", models.CharField(max_length=150)),
                ("ul_id", models.CharField(max_length=150)),
                ("miejscowosc", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
                (
                    "gmina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.gmina"
                    ),
                ),
                (
                    "powiat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.powiat"
                    ),
                ),
                (
                    "wojewodztwo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.wojewodztwo",
                    ),
                ),
            ],
        ),
    ]
