# Generated by Django 4.1.4 on 2022-12-30 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_wojewodztwo_woj_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Powiat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("pow_id", models.CharField(max_length=150, unique=True)),
                ("status_on_day", models.CharField(max_length=150)),
                (
                    "wojewodztwo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.wojewodztwo",
                    ),
                ),
            ],
        ),
    ]
