# Generated by Django 4.1.4 on 2022-12-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_powiat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powiat",
            name="pow_id",
            field=models.CharField(max_length=150),
        ),
    ]
