# Generated by Django 4.1.4 on 2022-12-31 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_powiat_pow_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gmina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("extra_name", models.CharField(max_length=150)),
                ("status_on_day", models.CharField(max_length=150)),
                ("gmi_id", models.CharField(max_length=150)),
                (
                    "powiat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.powiat"
                    ),
                ),
                (
                    "wojewodztwo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.wojewodztwo",
                    ),
                ),
            ],
        ),
    ]
