# Generated by Django 4.1.4 on 2023-01-01 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_miejscowosc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="miejscowosc",
            name="extra_name",
        ),
        migrations.RemoveField(
            model_name="miejscowosc",
            name="status_on_day",
        ),
    ]
